name: rtsp-to-webrtsp
base: core22
summary: Media URLs ReStreamer (over WebRTC)
adopt-info: restreamer
description: |
  Intended to help play RTSP streams from IP Cams (and some other URL types) in browsers. Also it can be used as Cloud DVR (https://github.com/WebRTSP/ReStreamer#how-to-use-it-as-cloud-dvr-for-ip-cam-not-accessible-directly)

  To try, install snap and open http://localhost:5080 in your browser.

  **Config file location:** /var/snap/rtsp-to-webrtsp/common/restreamer.conf

  **Online demo:** http://ipcam.stream:5080
license: GPL-3.0
grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

layout:
  /opt/rtsp-to-webrtsp/lib:
    symlink: $SNAP/opt/rtsp-to-webrtsp/lib

parts:
  meson-deps:
    plugin: nil
    override-build: |
      pip install meson
    build-packages:
      - python3-pip
  gstreamer:
    plugin: meson
    source: https://github.com/RSATom/gstreamer.git
    source-branch: 1.22
    after:
      - meson-deps
    build-packages:
      - ninja-build
      - flex
      - bison
      - nasm
      - libsrtp2-dev
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - -Dauto_features=disabled
      - -Dpython=disabled
      - -Dlibav=disabled
      - -Dlibnice=enabled
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dugly=disabled
      - -Dbad=enabled
      - -Ddevtools=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dqt5=disabled
      - -Dtools=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=disabled
      - -Dnls=disabled
      - -Ddoc=disabled
      - -Dgstreamer:ptp-helper-permissions=none
      - -Dlibnice:gupnp=auto
      - -Dlibnice:gstreamer=enabled
      - -Dlibnice:crypto-library=auto
      - -Dgst-plugins-base:playback=enabled
      - -Dgst-plugins-base:typefind=enabled
      - -Dgst-plugins-good:rtsp=enabled
      - -Dgst-plugins-good:rtpmanager=enabled
      - -Dgst-plugins-good:udp=enabled
      - -Dgst-plugins-good:rtp=enabled
      - -Dgst-plugins-good:debugutils=enabled
      - -Dgst-plugins-good:multifile=enabled
      - -Dgst-plugins-good:isomp4=enabled
      - -Dgst-plugins-bad:webrtc=enabled
      - -Dgst-plugins-bad:codectimestamper=enabled
      - -Dgst-plugins-bad:videoparsers=enabled
      - -Dgst-plugins-bad:dtls=enabled
      - -Dgst-plugins-bad:srtp=enabled
    stage-packages:
      - libunwind8
      - libdw1
      - libgupnp-1.2-1
      - libgupnp-igd-1.0-4
      - libsrtp2-1
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v4.3-stable
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DLWS_WITH_GLIB=ON
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - libssl-dev
      - libglib2.0-dev
    stage-packages:
      - libssl3
  coturn:
    plugin: autotools
    source: https://github.com/WebRTSP/coturn.git
    source-branch: stable
    build-environment:
      - TURN_NO_SYSTEMD: yes
      - TURN_NO_MYSQL: yes
      - TURN_NO_PQ: yes
      - TURN_NO_MYSQL: yes
      - TURN_NO_MONGO: yes
      - TURN_NO_HIREDIS: yes
      - TURN_NO_PROMETHEUS: yes
    autotools-configure-parameters:
      - --prefix=/opt/coturn
      - --turndb=/var/snap/${SNAPCRAFT_PROJECT_NAME}/common
    build-packages:
      - libevent-dev
      - libsqlite3-dev
    stage-packages:
      - libevent-2.1-7
      - libevent-core-2.1-7
      - libevent-extra-2.1-7
      - libevent-openssl-2.1-7
      - libevent-pthreads-2.1-7
  coturn.sh:
    plugin: dump
    source: .
    organize:
        coturn.sh: opt/coturn/bin/
    stage:
        - opt/coturn/bin/coturn.sh
  restreamer:
    plugin: cmake
    source-type: git
    source: .
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:$SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/pkgconfig:${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}:${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - lws
      - gstreamer
    build-packages:
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - gsoap
      - libgsoap-dev
      - libmicrohttpd-dev
    stage-packages:
      - libconfig9
      - libspdlog1
      - libgsoap-2.8.117
      - libmicrohttpd12
      - pwgen
apps:
  ReStreamer:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/ReStreamer
    daemon: simple
    plugs:
      - network-bind
      - network
    restart-delay: 3s
    environment:
      PATH: $SNAP/opt/coturn/bin:$PATH
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}:$LD_LIBRARY_PATH
      GST_DEBUG: 2
      GST_DEBUG_NO_COLOR: 1
      GST_PLUGIN_PATH: $SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/opt/${SNAP_NAME}/lib/${SNAPCRAFT_ARCH_TRIPLET}/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/opt/${SNAP_NAME}/libexec/gstreamer-1.0/gst-plugin-scanner
  Coturn:
    command: opt/coturn/bin/coturn.sh
    daemon: simple
    plugs:
      - network-bind
      - network
    install-mode: disable
    restart-delay: 3s
    after:
      - ReStreamer
