name: rtsp-to-webrtsp
base: core24
summary: Media URLs ReStreamer (over WebRTC)
adopt-info: restreamer
description: |
  Intended to help play RTSP streams from IP Cams (and some other URL types) in browsers.
  
  To try, install snap and open http://localhost:5080 in your browser.
  
  * **Config file location:** /var/snap/rtsp-to-webrtsp/common/restreamer.conf
  * **Online demo:** http://ipcam.stream:5080
  * **How to use it as Cloud DVR:** https://github.com/WebRTSP/ReStreamer#how-to-use-it-as-cloud-dvr-for-ip-cam-not-accessible-directly
  * **How to use it behind router/NAT:** https://github.com/WebRTSP/ReStreamer#how-to-access-it-behind-routernat-with-port-forwarding
  * **How to use it to access IP Cam behind router/NAT:** https://github.com/WebRTSP/ReStreamer#how-to-use-it-to-access-ip-cam-not-accessible-directly-and-without-any-port-forwarding
license: GPL-3.0
grade: devel
confinement: strict

platforms:
  amd64:
  arm64:

layout:
  /opt/${SNAPCRAFT_PROJECT_NAME}/lib:
    symlink: $SNAP/opt/${SNAPCRAFT_PROJECT_NAME}/lib

parts:
  gstreamer:
    plugin: meson
    source: https://gitlab.freedesktop.org/gstreamer/gstreamer.git
    source-branch: 1.24
    build-packages:
      - meson
      - ninja-build
      - flex
      - bison
      - nasm
      - libsrtp2-dev
    meson-parameters:
      - --prefix=/opt/${SNAPCRAFT_PROJECT_NAME}
      - -Dauto_features=disabled
      - -Dpython=disabled
      - -Dlibav=disabled
      - -Ddevtools=disabled
      - -Drtsp_server=disabled
      - -Dgst-examples=disabled
      - -Dqt5=disabled
      - -Dqt6=disabled
      - -Dtests=disabled
      - -Dexamples=disabled
      - -Dintrospection=disabled
      - -Dnls=disabled
      - -Ddoc=disabled
      - -Dgstreamer:ptp-helper-permissions=none
      - -Dgpl=disabled
      - -Dtools=enabled # required for orc
      - -Dorc=enabled
      - -Dorc-source=subproject
      - -Dwebrtc=enabled
      - -Dlibnice=enabled
      - -Dlibnice:gupnp=auto
      - -Dlibnice:gstreamer=enabled
      - -Dlibnice:crypto-library=auto
      - -Dbase=enabled
      - -Dgst-plugins-base:playback=enabled
      - -Dgst-plugins-base:typefind=enabled
      - -Dgood=enabled
      - -Dgst-plugins-good:rtsp=enabled
      - -Dgst-plugins-good:rtpmanager=enabled
      - -Dgst-plugins-good:udp=enabled
      - -Dgst-plugins-good:rtp=enabled
      - -Dgst-plugins-good:debugutils=enabled
      - -Dgst-plugins-good:multifile=enabled
      - -Dgst-plugins-good:isomp4=enabled
      - -Dbad=enabled
      - -Dgst-plugins-bad:webrtc=enabled
      - -Dgst-plugins-bad:codectimestamper=enabled
      - -Dgst-plugins-bad:videoparsers=enabled
      - -Dgst-plugins-bad:dtls=enabled
      - -Dgst-plugins-bad:srtp=enabled
      - -Dgst-plugins-bad:sctp=enabled
      - -Dugly=disabled
    stage-packages:
      - libunwind8
      - libdw1
      - libupnp17t64
      - libgupnp-igd-1.6-0
      - libsrtp2-1
  coturn:
    plugin: autotools
    source: https://github.com/WebRTSP/coturn.git
    source-branch: stable
    build-environment:
      - TURN_NO_SYSTEMD: "yes"
      - TURN_NO_MYSQL: "yes"
      - TURN_NO_PQ: "yes"
      - TURN_NO_MYSQL: "yes"
      - TURN_NO_MONGO: "yes"
      - TURN_NO_HIREDIS: "yes"
      - TURN_NO_PROMETHEUS: "yes"
    autotools-configure-parameters:
      - --prefix=/opt/coturn
      - --turndb=/var/snap/${SNAPCRAFT_PROJECT_NAME}/common
    build-packages:
      - libevent-dev
      - libsqlite3-dev
    stage-packages:
      - libevent-2.1-7
      - libevent-core-2.1-7
      - libevent-extra-2.1-7
      - libevent-openssl-2.1-7
      - libevent-pthreads-2.1-7
  coturn.sh:
    plugin: dump
    source: .
    organize:
        coturn.sh: opt/coturn/bin/
    stage:
        - opt/coturn/bin/coturn.sh
  restreamer:
    plugin: cmake
    source-type: git
    source: .
    build-environment:
      - PKG_CONFIG_PATH: ${SNAPCRAFT_STAGE}/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:${SNAPCRAFT_STAGE}/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig:${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}
      - LD_LIBRARY_PATH: ${SNAPCRAFT_STAGE}/opt/${SNAPCRAFT_PROJECT_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    override-pull: |
        craftctl default
        craftctl set version="$(git describe --always)"
    after:
      - gstreamer
    build-packages:
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
      - gsoap
      - libgsoap-dev
      - libmicrohttpd-dev
      - libwebsockets-dev
    stage-packages:
      - libconfig9
      - libspdlog1.12
      - libgsoap-2.8.132t64
      - libmicrohttpd12
      - libwebsockets19t64
      - libwebsockets-evlib-glib
      - pwgen
apps:
  ReStreamer:
    command: opt/${SNAPCRAFT_PROJECT_NAME}/bin/ReStreamer
    daemon: simple
    plugs:
      - network-bind
      - network
    restart-delay: 3s
    environment:
      PATH: $SNAP/opt/coturn/bin:${PATH}
      LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib:$SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${LD_LIBRARY_PATH}
      GST_DEBUG: 2
      GST_DEBUG_NO_COLOR: 1
      GST_PLUGIN_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/opt/${SNAP_NAME}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/opt/${SNAP_NAME}/libexec/gstreamer-1.0/gst-plugin-scanner
  Coturn:
    command: opt/coturn/bin/coturn.sh
    daemon: simple
    plugs:
      - network-bind
      - network
    install-mode: disable
    restart-delay: 3s
    after:
      - ReStreamer
