#!/bin/sh -e

umask 027

cp "${SNAP}/opt/coturn/etc/turnserver.conf.default" "${SNAP_COMMON}/turnserver.conf"
cp "${SNAP}/opt/${SNAP_NAME}/etc/restreamer.conf.sample" "${SNAP_COMMON}/restreamer.conf"
